# Generated by Django 5.1.1 on 2024-10-06 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
